#!/bin/bash

arr=(10 20 30 40 50)

echo "Enter element to search:"
read key

found=0

for i in "${arr[@]}"
do
    if [ $i -eq $key ]
    then
        found=1
        break
    fi
done

if [ $found -eq 1 ]
then
    echo "Element Found."
else
    echo "Element Not Found."
fi
